### ISSUE TITLE
Enhancement/Feature request: qBittorrent support

### ISSUE THREAD

**Issue by jonskoglund** [glorious1/manual-connections#11]
Thank you very much for sharing your code. I managed to get it running with very little changes to the code. I'm running this on TrueNAS-12.0-U4. Currently your fork only supports Transmission. Is there any change that you will be supporting qBittorrent? For now I will be using Transmission Remote GUI but the UI of qBittorrent is more feature complete than transmission. Supporting that package would be very very nice. 
@Roman2K did something with qBT callback. Maybe that can help? See here: https://github.com/Roman2K/docker-pia

**Comment by Roman2K** [comment]
Hopefully my fork can be of use, it's been working problem-free for 6 months. Differences from upstream:
* List: [this section](https://github.com/Roman2K/docker-pia#roman2k-fork) of the README
* Code: [diff](https://github.com/pia-foss/manual-connections/compare/master...Roman2K:master?expand=1)

docker-compose:

```yaml
  vpn:
    image: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - caddy
    environment:
      PIA_USER: secret
      PIA_PASS: secret
      PIA_ON_PF_EXEC: ./on-pf-up-qbt
      ON_PF_QBT_LOGIN: secret
      ON_PF_QBT_PASSWORD: secret
      ON_PF_QBT_URL: "https://secret:secret@qbt.some-domain"
    labels:
      # Caddy routes generated with https://github.com/Roman2K/hostmap
      hostmap.as.qbt.enable: true
      hostmap.as.qbt.port: 8080
      hostmap.as.qbt.users: roman
```
